Ability to decorate new rootUrl hostname
gemini-testing/gemini-tunnel pull request #13
Opened 2016-09-30 15:40 UTC by j0tunn

2016-09-30 15:40 UTC, j0tunn commented
@sipayRT @tormozz48 @eGavr

2016-09-30 15:44 UTC, j0tunn commented
падает линтер изза es6

2016-09-30 16:21 UTC, sipayRT requested changes

2016-09-30 16:21 UTC, sipayRT commented on index.js
> +        hostDecorator: (host) => opts.host
тут линтер должен был на тебя ругнуться за то, что передаешь аргумент, но не используешь его

2016-09-30 16:21 UTC, sipayRT commented on test/index.js
> +                const gemini = mimicGeminiConfig({ browserId: 'bro' });
тут (и ниже) линте поругается на пробелы в объекте

2016-09-30 16:21 UTC, sipayRT commented on test/index.js
> +            it('should use host value by default', () => {
давай этот тест будет идти первым - логично дефолтное поведение тестировать в самом начале

2016-09-30 16:23 UTC, sipayRT commented on package.json
> +    "node": ">= 4.0.0"
если отказываемся от 0.10,  то в [.travis.yml](https://github.com/gemini-testing/gemini-tunnel/blob/master/.travis.yml#L4) нужно выгасить прогон тестов в этой версии

2016-09-30 19:46 UTC, j0tunn commented on test/index.js
> +                const gemini = mimicGeminiConfig({ browserId: 'bro' });
я это скопировал из какого-то теста ниже, и там он не ругался

2016-09-30 19:49 UTC, j0tunn commented
:up: насчет линтера - я там завел задачку на вкручивание сюда eslint + перевод на es6. Сейчас не до того

2016-10-03 09:59 UTC, sipayRT approved these changes

2016-10-03 09:59 UTC, sipayRT commented on test/index.js
> +                const gemini = mimicGeminiConfig({ browserId: 'bro' });
я так понимаю, что линтерами мы будем заниматься в отдельной задаче?

2016-10-03 10:01 UTC, merged